### ISSUE TITLE
Confusion between cluster=True and clustering=True

### ISSUE THREAD

**Issue by nwmoriarty** [qrefine/qrefine#12]
This may not be a purely Q|R issue but when using cluster=True there is no clustering and when using clustering=True this is clustering. It's strange behaviour via the PHIL parameters that may cause others problems.

**Comment by mpwaller** [comment]
@nwmoriarty 

when I run:

```qr.refine 3dtj_complete.pdb 3dtj-sf.mtz restraints=cctbx cluster=true```

I get 

```RuntimeError: Error interpreting cluster.maxnum_residues_in_cluster="true" as a numeric expression (command line argument, line 1)```

But when I use the correct PHIL parameter

```qr.refine 3dtj_complete.pdb 3dtj-sf.mtz restraints=cctbx clustering=true``` 

It works. 

Can we close this issue?

**Comment by nwmoriarty** [comment]
This is the correct behaviour.
