### ISSUE TITLE
p26 dynamic snapshots and mtz data files

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qrefine#13]
In run_perturb.py and run_compute_fobs.py, the input file path was just changed from 01_reordered_box to 01b_fixSplit by me.
Do we need to regenerate mtz files and perturbed structures?

**Comment by pafonine** [comment]
Since this takes no time, I suggest we fix the script and re-generate files.
Pavel

**Comment by mpwaller** [comment]
This was solved
