### ISSUE TITLE
Expand not used when clustering is turned off.

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#13]
A super sphere should be created with/without clustering. 

Currently, it is only done in the fragment.py file.

**Comment by mpwaller** [comment]
@pafonine this would also be nice to have for the ANI models. I understand significant refactoring is needed.

**Comment by pafonine** [comment]
Hi Mark,
I attempted to look into this several times hoping to do it in one go in 
one day.. But.. This is highly intertwined with Min's code. I can not do 
it alone on my own without fully refactoring Min's contribution to QR 
code base. It should be a concerted move done by Min and me (and you at 
least). Also, it is all the same when altlocs are involved, not only 
expansion to account for periodicity and symmetry. It is a complex but 
fully doable issue. It is one of those when spending together a few full 
days sharing the keyboard gets this solved.

My proposal is to wait till Min has her clustering code re-done, and 
then take care of this when integrating her new code into QR.

May be we should dedicate a next QR meeting just to do this -- it would 
be worthwhile. This is a fully defined concrete goal with fully 
predictable ETA, plus super-important for the project. Shall we aim at it?

Pavel

**Comment by mpwaller** [comment]
Agreed, we need this because it is blocking development.

**Comment by mpwaller** [comment]
Issue resolved.
