### ISSUE TITLE
qrefine on SSC

### ISSUE THREAD

**Issue by biczysko** [qrefine/qrefine#14]
phenix.python qrefine_test.py ../p26/03_perturbed/191_WG03-new/0.3/0.pdb ../p26/02_mtz/191_WG03-new.mtz restraints=qm running on SSC with Gaussian HF/6-31*G. I will post results ASAP

**Comment by mpwaller** [comment]
Great news, keep us updated!

**Comment by biczysko** [comment]
Some general problems with SSC..., all jobs (even 'normal' Gaussian ones) crashed due to the lack of memory in the account...

**Comment by mpwaller** [comment]
any luck in getting this sorted out?

**Comment by mpwaller** [comment]
This is working, I saw it running yesterday. Closed.
