### ISSUE TITLE
Confusing logical in qr_tools.py

### ISSUE THREAD

**Issue by nwmoriarty** [qrefine/qrefine#15]
When Pavel and I run tst_13.py is fails in the qr_toolbox function. It is failing when addon is None. Not sure why it's changed but the logical seems strange. At line 130

if 'gcp' in addon.lower():

but "in" should be a check in a list not a string. Perhaps it should be

if addon is not None and addon.lower()=='gcp:

**Comment by mpwaller** [comment]
@hokru  what is the status on this?
