### ISSUE TITLE
r-factors are increasing during refinement

### ISSUE THREAD

**Issue by zhengmin317** [qrefine/qrefine#15]
The command  for 2OL9 cctbx refinement: phenix.python ./qrefine/qrefine.py  ./mtz/2ol9.mtz ./pdb/2ol9-H.pdb restraints=cctbx number_of_macro_cycles=50.
The result shows r-factors are increasing during refinement.
![screen shot 2016-01-20 at 08 54 41](https://cloud.githubusercontent.com/assets/16145132/12442972/aa18e138-bf54-11e5-827c-928fe7b53d68.png)

**Comment by mpwaller** [comment]
Hi guys,
 has this been resolved? 
cheers,
Mark
