### ISSUE TITLE
logging level

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#17]
improve logging especially in the quantum wrappers to better see when/where problems are occurring.

**Comment by mpwaller** [comment]
@pafonine can you propagate the log object down to the wrappers?  and also the debug flag, then we can better debug problems that originate deep down in the plugin wrappers.

**Comment by pafonine** [comment]
Logging is a huge issue and we should re-think and re-do it for finer granularity and deeper access.

**Comment by mpwaller** [comment]
Closing this issue, will raise it again when we have gathered requirements.
