### ISSUE TITLE
complete minimal documentation

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#20]
list of minimal requirements
 - [x] installation
 - [x] basic QR process
 - [x] keyword overview (several missing entries)
 - [x] at least 1 detailed example
 - [x] basic HOWTO for each QM interface
   - [x] terachem 
   - [x] gaussian
   - [x] mopac
   - [x] turbomole
   - [x] ORCA
   - [x] xtb 
   - [x] ani / torch-ani
   - [x] qm_addon

Please post additional suggestions and/or completion of a task. I will then update the OP.

**Comment by hokru** [comment]
useful command:
`phenix_html.rebuild_docs process_all_files=1 top_dir=modules/qrefine`

**Comment by hokru** [comment]
updated wiki, i.e. mostly deleting the documentation since it resides now on qrefine.com

Notable change is a developer how-to to remind ourselves of small work flows.

**Comment by mpwaller** [comment]
added some more help strings, rebuilt docs, and deployed them to webserver.

**Comment by mpwaller** [comment]
@pavel when you get a chance can you please add the final missing .help strings in the phil keywords of qr.py, for example:

```
refinement_target_name = *ml ls_wunit_k1
    .type = choice
number_of_weight_search_cycles=50
    .type = int
 data_weight=None
    .type = float
  choose_best_use_r_work = False
    .type = bool
  skip_initial_weight_optimization = False
    .type = bool
  adjust_restraints_weight_scale_value = 2
    .type = float
  max_iterations_weight = 50
    .type = int
  max_iterations_refine = 50
    .type = int
update_all_scales = True
    .type = bool
data_weight=None
    .type = float
  choose_best_use_r_work = False
    .type = bool
  skip_initial_weight_optimization = False
    .type = bool
  adjust_restraints_weight_scale_value = 2
    .type = float
  max_iterations_weight = 50
    .type = int
  max_iterations_refine = 50
    .type = int
```

and 

```
output_file_name_prefix = None
  .type = str
output_folder_name = "pdb"
  .type = str
```

Once these help strings are added, please feel free to close this issue.

**Comment by pafonine** [comment]
Sure, will do it once get back from West Virginia.
Pavel

**Comment by pavel** [comment]
@mpwaller Thanks for notifying me, but it does not seem that I'm involved in this project in any way.

https://blog.github.com/2011-03-23-mention-somebody-they-re-notified/

**Comment by mpwaller** [comment]
@pavel sorry, wrong pavel.

**Comment by mpwaller** [comment]
Done.
