### ISSUE TITLE
implement a versioning scheme for qrefine

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#21]

**Comment by hokru** [comment]
suggestion:
 `major`.`minor`-`patch level`

manually tagging with git: `git tag -a v1.0 -m 'version 1.0'`
rest automatic with describe: `git describe --abbrev=4 --dirty --always --tags`

E.g. after 1 commit this gives:
`v1.0-1-gab2f`, where 1 indicates how many commits have been made and the rest is the git hash.

The string itself could be written into the qr code during the bootstrap process.

**Comment by mpwaller** [comment]
020af5bc10e6580fdb14a20d2f2c3c623e841d36

Thanks @hokru and @nwmoriarty !
