### ISSUE TITLE
improve versioning

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#24]
The current version string necessarily always lags behind and can be easily overwritten via different commits. To have the correct version displayed a user is forced to run the script after every `git clone` or `git pull`.

**Comment by hokru** [comment]
MolSSI recommends https://github.com/warner/python-versioneer

**Comment by mpwaller** [comment]
👍 +1

**Comment by nwmoriarty** [comment]
Works for me.

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by mpwaller** [comment]
@hokru what is the status on this?

**Comment by hokru** [comment]
I didn't investigate further.
