### ISSUE TITLE
[Linux] mopac issue with provided custom libiompo5.so 

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#26]
**Describe the bug**
mopac on Linux has troubles finding its own `libiomp5.so` library.  Providing the correct path in `LD_LIBRARY_PATH` is ignored or not used at all(?). For Darwin/Mac the threading library is not needed or statically linked and thus not an issue.
Related to #18. 

The issue can be identified when, e.g., setting `MOPAC_COMMAND="ldd /path-to-mopac/MOPAC2016.exe"`

A workaround is explicitly providing the library during the mopac command:
`export MOPAC_COMMAND="LD_PRELOAD=/usr/qc/mopac2016//libiomp5.so mopac"`

Ideas on a more proper solution?

**Comment by nwmoriarty** [comment]
My solution on our cluster was to use a shell script called mopac.csh that was pointed to by $MOPAC_COMMAND. I can see an argument for either but this way allows for different paths and the license as well.

📁 
#!/bin/csh
setenv LD_LIBRARY_PATH /net/cci/xp/mopac
setenv MOPAC_LICENSE /net/cci/xp/mopac
/net/cci/xp/mopac/MOPAC2016.exe $1
exit
