### ISSUE TITLE
stpmax=0.2 makes tst_00 and tst_01 fail

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#27]
I tired updating the default stpmax to be 0.2. However, when running the test suite, the first two tests fail.

**To Reproduce**
1. change the default stpmax=0.2 in qr.py
1. Go to test folder
2.  run `qr.test --nproc=8` 
4. See error:

qr.refine m00_good.mtz /Users/mark/PycharmProjects/phenix/phenix-dev-3386/modules/qrefine/tests/unit/data_files/m00_poor.pdb restraints=cctbx output_folder_name=tst_00 > tst_00.log
tst_00 FAILED Cannot open file for reading: "tst_00/m00_poor_refined.pdb"
  [Errno 2] No such file or directory: 'tst_00/m00_poor_refined.pdb'
       Total time:  18.19 (s)
qr.refine m00_good.mtz /Users/mark/PycharmProjects/phenix/phenix-dev-3386/modules/qrefine/tests/unit/data_files/m00_poor.pdb restraints=cctbx mode=opt output_folder_name=tst_01 > tst_01.log
tst_01 FAILED 
       Total time:  25.34 (s)

**Suggested behavior**
We should adjust the values in the tst_00 and tst_01 to make it pass with 0.2 stpmax: 

tst_00.py
fmodel.r_work() < 0.04
r_final-fmodel.r_work())<0.0005

tst_01.py
get_bond_rmsd('m00_poor.pdb' ) > 0.1
get_bond_rmsd('m00_poor_refined.pdb') < 0.0009 < 0.0009

**Desktop (please complete the following information):**
 - OS: Mac OS 10.14.2
 - Version qr commit caused problem a7e1184  changed back in 5fdbd17

**Comment by pafonine** [comment]
I've been thinking about it.. Are we all agree that this is a good 
default? Can we think of a good simple test that we confirm it is an ok 
default (preferably using CCTBX restraints, so it is quick).

I will look into failing tests when using 0.2 now. I suspect they fail 
because when using stpmax=0.2 model does not move enough (given set 
number of optimization/refinement cycles) and so then refined/optimized 
model does not match the test expectations.

Pavel

**Comment by biczysko** [comment]
1. All tests I have done (xtb and cctbx) for 1us0 "old helix" considered stpmax=3.0 and stpmax=0.5 along with clustering=True/False . 

Stpmax=0.5 shown already some problems.

2. The set-up was not default with the common set of options as follows:
-----------
qr.refine max_bond_rmsd=0.04 number_of_refine_cycles=10 max_iterations_weight=25 max_iterations_refine=100 number_of_refine_cycles=10 pre_opt=true adjust_restraints_weight_scale_value=4 choose_best_use_r_work=true opt_log=1
----------
3. For cctbx stpmax=0.5 + larger perturbations both opt/refine ended with:
------
lbfgs minimizer exception: lbfgs error: Line search failed: The step is at the upper bound stpmax()
------
4. For xtb stpmax=0.5 + larger perturbations AND cluster=False both opt/refine ended very quickly,
without error, but keeping large perturbations.

Note: for xtb all computations were done with qradient_only=False 
We do now with gradient_only=True, and also with stpmax=0.2

I am still looking at the files will send upgrade with pics ASAP

Goska

**Comment by mpwaller** [comment]
Done. Tests now pass with this default.
