### ISSUE TITLE
Update README.md to provide more details 

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#29]
# QM Interfaces
### -	QR does not include the QM codes required to run optimization or refinement. You have to install them yourself.
Once you have installed them, you need to set an environment variable to allow QR to know where to find it.
Below is a set of examples that give you and idea of how to get started, please modify the locations to match your own installation. 

| QM Code         | Example Setup for Bash                                                        | Available at          |
| -------------   |-------------|-------------| 
| ANI             | export NC_ROOT="/home/olexandr/notebooks/ASE_ANI"                             |   https://github.com/isayev/ASE_ANI                      |
|                 | export LD_LIBRARY_PATH="$NC_ROOT/lib:$LD_LIBRARY_PATH"                        |                         |
|                 | export PYTHONPATH="$NC_ROOT/lib:$PYTHONPATH"                                  |                         |    
| Gaussian        | export g16root=/opt/qmsoft/g16.                                      | http://gaussian.com/     | 
|                 | . $g16root/g16/bsd/g16.profile                                       |                          |
|                 | export PATH=$PATH:/opt/qmsoft/g16/bsd:/opt/qmsoft/g16/local          |
| Mopac           | export MOPAC_COMMAND=/opt/mopac/MOPAC2016.exe                        | http://openmopac.net/   |
| Orca            | export Orca_COMMAND=/opt/qmsoft/orca/orca.                           | https://orcaforum.kofo.mpg.de/app.php/portal | 
| PyScf           |                                                                      | https://sunqm.github.io/pyscf/install.html   |
| Terachem        | source /public/qmsoft/TeraChem/SetTCVars.sh                          | http://www.petachem.com/ |
|                 | export TeraChem_COMMAND=/opt/qmsoft/tc/1.93/TeraChem/bin/terachem    |                          |   
| Torchani        |                                                                      | https://github.com/aiqm/torchani                      |
| Turbomole       |                                                                      |  http://www.turbomole.com/                        |
| xtb             | export XTBHOME=/home/qr/XTB                                          | https://www.chemie.uni-bonn.de/pctc/mulliken-center/software/xtb/xtb |
|                 | source XTB/Config_xtb_env.bash                                       |                           |

@hokru can you please add details for turbomole?
@yanting0928 can you please check the details for ani and torchani?

**Comment by hokru** [comment]
IMO this should be in the docs, not readme.

**Comment by mpwaller** [comment]
@hokru no problem, we can just add a hyperlink on the README.

**Comment by yanting0928** [comment]
actually, In my setting ,I have nothing in bash for ani and torchani
