### ISSUE TITLE
confusion about tolerance in tst_13

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#33]
Mentioned unit test compares the full vs the clustered gradient using cctbx's `approx_equal` function
https://github.com/qrefine/qrefine/blob/master/tests/unit/tst_13.py#L75

Following the definition of approx_equal (`libtbx/test_utils/__init__.py`) the `tolerance` takes a single double float value. Here however it gets a `vec3_double` times `0.05`. Is that even a number in the end?

And what was the intention here?
Comparing the closeness of the two gradients using a dynamic tolerance of `gradient component*0.05` to account for small and large gradient values? If so, the attached patch (`git apply <filename>`) does something along those lines, modifying tst_13.py. It shows few too large errors, though.

Do I just not understand some functionality here, or is that a bug?
Tagging @mpwaller and @pafonine
[tst13.patch.txt](https://github.com/qrefine/qrefine/files/2837234/tst13.patch.txt)

**Comment by pafonine** [comment]
Hi Holger,

the line #75:

assertapprox_equal(list(g_entire.as_double()),list(g_cluster.as_double()) 
, g_entire*0.05)

does not make sense to me. Indeed, approx_equal is meant to compare two 
arrays (of various types: from native Python list/tuples to flex arrays 
and perhaps even numpy) or two single numbers up to a specified 
tolerance, which is the third argument in the call and by default is 
1.e-6 if I remember correctly.

Having said this,
- there is no need to convert flex.double to list; AND
- tolerance being an array does not make sense to me;
- the fact that approx_equal swallows this without an error I think is a 
bug or a highly unfortunate feature. Indeed:

 >>>
 >>> from scitbx.array_family import flex
 >>> from libtbx.test_utils import approx_equal
 >>> x = flex.double([1,2,3])
 >>> y = flex.double([3,2,1])
 >>> approx_equal(x,x)
True
 >>> approx_equal(x,y)
approx_equal eps: 1e-06
approx_equal multiplier: 10000000000.0
   1.0 approx_equal ERROR
   3.0 approx_equal ERROR

   2.0
   2.0

   3.0 approx_equal ERROR
   1.0 approx_equal ERROR

False
 >>> approx_equal(x,x,y)
True
 >>>

Pavel

**Comment by hokru** [comment]
For documentation reasons, the following gradient components fail to agree to 5% of the value.
```
 index error tolerance
 37 0.078262 0.01683505
 116 0.704005 0.1276611
 118 0.162156 0.0627193
 138 0.509158 0.3706716
 141 0.151051 0.0042658
```

Using `two_buffers=True` is accurate enough and will be enabled in an upcoming commit.
