### ISSUE TITLE
qr.build_interfaces

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#37]
Complete checking for each  of the wrappers in qr.build_interfaces. 

So far only mopac and terachem are checked.

TODO:

- [x] XTB

- [x] Turbomole

- [x] Gaussian

- [x] Orca

- [x] PySCF

- [x] ANI

- [x] TorchANI

**Comment by mpwaller** [comment]
done

**Comment by mpwaller** [comment]
@nwmoriarty could you add this to the bootstrap.py so that new users will be more aware that they need to install qm engines.

**Comment by nwmoriarty** [comment]
Added the command to bootstrap. Can see result in next cycle. 🇦🇺
