### ISSUE TITLE
Python 3 support

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#38]
**Is your feature request related to a problem? Please describe.**
We should start making plans to support python3 

**Describe the solution you'd like**
I would like to have dual support for python2 and python3

**Describe alternatives you've considered**
We are being blocked from using libraries that are supporting python3 only. 

**Additional context**
I understand that the libraries we already depend on are still python2.

**Comment by pafonine** [comment]
Given rather small size of QR code base, I believe we can convert it to 
Python3 in one go using a few days. However, making sure it is backwards 
compatible may require some investigation. Best is to ask Billy who is 
in charge for this for entire Phenix and is likely to know the answer.

Pavel

**Comment by hokru** [comment]
What libraries (besides phenix) are python2 and won't make the switch? Long term python2 support does not make much sense given the eco system change (https://pythonclock.org/)

**Comment by mpwaller** [comment]
@pafonine  ok I contact Billy

@hokru  cctbx and some tools in phenix

**Comment by mpwaller** [comment]
https://github.com/cctbx/python3

**Comment by mpwaller** [comment]
https://github.com/cctbx/cctbx_project/projects

**Comment by hokru** [comment]
A tentatively start of the conversion process can be found in the `qr_py3` branch https://github.com/qrefine/qrefine/tree/qr_py3

**Comment by hokru** [comment]
I don't manage to build cctbx via bootstrap in a conda python3 environment on my mac.
Not sure how I can test the branch in another way.

**Comment by bkpoon** [comment]
@hokru What command are you using for building?

**Comment by hokru** [comment]
@bkpoon It's been a while.
I think I used the bootstrap as mentioned in the README of cctbx_project
`python3 bootstrap.py` or `python3 boostrap.py --python3`

I remember looking for a conda package, but I dont think I found one back then.

**Comment by bkpoon** [comment]
Can you try this bootstrap command?
```
python bootstrap.py --use-conda --python 37
```
We've removed the `--python3` flag. You can choose Python 3.6, 3.7, and 3.8. Just remove the "." (e.g. 3.7 becomes 37).

**Comment by hokru** [comment]
I pulled the latest cctbx changes today and ran the suggested command.
The installation was successful! Many thanks @bkpoon 

---

On topic:
 Looks like I need to fix more `import` statements to python3 conventions.

**Comment by hokru** [comment]
status update

- after installing cctbx one needs to fix this error:
`mmtbx.monomer_library.server.MonomerLibraryServerError: Cannot find CCP4 monomer library. Please define one of these environment variables: MMTBX_CCP4_MONOMER_LIB, CLIBD_MON`
For this (as found in a years old mailing list post) I moved `chem_data` from a phenix installation into the `modules` folder. 

- `qr.test` executes (yay!) meaning at least the principle parsing with python3 is OK

- following unique errors popping up:
  * tst_00 FAILED name 'xrange' is not defined
  * tst_07 FAILED 'ascii' codec can't decode byte 0xa2 in position 4: ordinal not in range(128)
  * tst_09 FAILED cannot import name 'letters' from 'string' (/home/kruse/usr-qc/cctbx/conda_base/lib/python3.7/string.py)
   * tst_23 FAILED name 'file' is not defined
   * tst_20 FAILED '<' not supported between instances of 'str' and 'empty'

tests 14 and 17 pass

**Comment by hokru** [comment]
Note: to compile `JPype1==0.6.3` in cctbx.python for OSX Catalina one needs to point `pip` to the correct `Python.h` location(later JPype versions seem to just work). This can be fixed by creating a symlink where `pip` expects the file:
```
ln -s <cctbx_root_dir>/conda_base/include <cctbx_root_dir>/conda_base/python.app/Contents/include
```

**Comment by hokru** [comment]
#65 switched QR to python3
