### ISSUE TITLE
qrefine/cctbx stats for 2ol9

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#4]
To test my qrefine/PHENIX/ASE installation, I ran this set of calculations on 2ol9 (as contained in the github repo):
 
cctbx:
macro_cycle   4 (sites) r_factor: 0.0563
Time: 4.3489

mopac:
macro_cycle   4 (sites) r_factor: 0.0574
Time: 1573.2784

26 mins vs 4 seconds is rather significant.

The structures are rather similar, only the waters and the the NH2 groups differ a little bit (via visualisation).

<img width="729" alt="screen shot 2016-01-15 at 11 18 01" src="https://cloud.githubusercontent.com/assets/13583117/12344575/bf55009c-bb79-11e5-9173-8560e31c0f3e.png">

**Comment by pafonine** [comment]
Yes, this is what I would expect? Anything surprising to you?
Pavel
