### ISSUE TITLE
unit tests not adapted to new command line arguments handling

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#46]
**Describe the bug**
30e77956d6 changes the way `mode=opt` expects the command line arguments to be. `.mtz` are now expected to be absent (formerly they were ignored?). Respective unit tests are failing.

Unclear to me if the `.mtz` should be (optionally) readable for optimisations or not.

**Comment by Mooooony** [comment]
If mode is opt, no data is expected.

**Comment by hokru** [comment]
Either the unit tests need to be adapted or the data file needs to be ignored.

**Comment by hokru** [comment]
currently working on fixing this and the failing `mode=gtest`, as it's connected

**Comment by Mooooony** [comment]
I forgot to include gtest mode.  What I am sure is that opt mode do not need any data. Which unit test failed?

**Comment by hokru** [comment]
Please don't make changes when I write I am working on this..
