### ISSUE TITLE
writing temporary pdb files for fragments&clusters

### ISSUE THREAD

**Issue by biczysko** [qrefine/qrefine#48]
**Is your feature request related to a problem? Please describe.**
Tests with different qr.refine options (like stpmax) create sometimes clusters with large charges, that is still not clear what happens and difficult to investigate without "latest" models for clusters/fragments in proper pdb format. 

**Describe the solution you'd like**
Files in pdb format written to the ase directory along with qm input files. It can be always written or to be an option.

**Comment by biczysko** [comment]
I think we had something like this already but got lost .. Now I have situation that there are big charges but seems that nothing wrong happens ...

**Comment by hokru** [comment]
started working on this

**Comment by hokru** [comment]
implementing a new phil parameter `cluster.save_clusters=True/False` that switches writing of the fragments+clusters on/off. Current default is `True` (=on). Data will be written to local directory `frag_pdbs`. Output like `gtest`

**Comment by biczysko** [comment]
@hokru  Thanks a lot !! I will test/use it ASAP
