### ISSUE TITLE
skipped tests and AssertionErrors

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#5]
I installed a recent phenix nightly build (dev-2919 few days old) and followed the bootstrap installation for qrefine, which seemed to install fine.
Some of the tests are skipped and some python errors appear: [test.output.txt](https://github.com/qrefine/qrefine/files/1406572/test.output.txt)

I only find few tst_xx.log files, not all. Where can I find more output from the tests? Why are some skipped?  How to interpret the assertion errors?

**Comment by pafonine** [comment]
Holger,

some tests may be skipped if you don't have required programs installed, 
such as QM engine (TeraChem, etc).

Hope others comment on failing tests.

Pavel

**Comment by nwmoriarty** [comment]
The test failure in tst_00 is consistent with the BuildBot but the error in
tst_18 is not.

What OS are you using? Do you have a QM package in mind?

Cheers

Nigel

---
Nigel W. Moriarty
Building 33R0349, Molecular Biophysics and Integrated Bioimaging
Lawrence Berkeley National Laboratory
Berkeley, CA 94720-8235
Phone : 510-486-5709     Email : NWMoriarty@LBL.gov
Fax   : 510-486-5909       Web  : CCI.LBL.gov

**Comment by hokru** [comment]
older Debian Linux. For now I plan to use Turbomole.

for tst_18 I have an output pointing to [calculater.py#L140](https://github.com/qrefine/qrefine/blob/master/calculator.py#L140)

> Initial r_work=0.0778 r_free=0.0756
> 
> ***********************************************************
> restart info will be stored in tst_18/h_altconf_complete.rst.pickle
> ***********************************************************
> 
> start   0 Rw: 0.0778 Rf: 0.0756 Rf-Rw: -0.0022 rmsd(b):  0.0175 rws:  1.0 n_fev: 0
> STOP: /home/kruse/Progs/phenix-dev-2919/modules/qrefine/calculator.py(140)
>
