### ISSUE TITLE
/frag_pdbs/n_cluster.pdb written before capping

### ISSUE THREAD

**Issue by biczysko** [qrefine/qrefine#56]
**Describe the bug**
The files n_frag.pdb written into /frag_pdbs/ do not include final capping, so do not match files used for the QM computations.

**To Reproduce**
Steps to reproduce the behavior (example):
1. run  qr.refine 4gif_test.pdb  mode=gtest g_mode=1 g_scan="15" restraints=qm  engine_name=xtb > log
3. look at  fragment "0" , in /frag_pdbs/0_frag.pdb is 654 atoms , in /ase/0/0_capping/xtb_tmp.xyz is 682 atoms.

**Expected behavior**
The /frag_pdbs/n_fragment.pdb  write molecular model identical to the one in /ase/n/n_capping/qm-input-file. 

[4gif_bug_gtest.zip](https://github.com/qrefine/qrefine/files/3546052/4gif_bug_gtest.zip)

**log file**
4gif_bug_gtest.log

 - Phenix Version [e.g. phenix-dev-3409]
 - qrefine Version [e.g. v1.0-114-g3318f9]

**Comment by hokru** [comment]
Right. They were not meant to be capped. But it can be added.

Do we need the capped PDBs also for `mode=refine/opt`? or is it sufficient for `mode=gtest`?

**Comment by biczysko** [comment]
I think that n_cluster.pdb should never be capped but for n_frag.pdb it is good to have it capped (or at best both, 1->not-yet-capped and 2->capped).
We need it also for `mode=refine/opt`.  I used `mode=gtest` example as it is fastest to reproduce.

**Comment by hokru** [comment]
OK sure. For `mode=gtest` it is fairly straightforward. For the other ones I need to figure out some details how to do it best.

**Comment by hokru** [comment]
addressed in commit bcefd1246004d213f93e96eaddeac540ec9d755c
