### ISSUE TITLE
JPype 0.7 breaks API

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#57]
The Jan.2019 update to 0.7 of Jpype broke the API in some places and it seems we are affected by it. It results in an error like this (Linux):

```
 File "/home/qr/phenix-1.17rc2-3611/modules/qrefine/plugin/yoink/pyoink.py", line 28, in __init__
    javaApplicationContext=JavaApplicationContext()
  File "/home/qr/phenix-1.17rc2-3611/conda_base/lib/python2.7/site-packages/jpype/_jobject.py", line 95, in __init__
    jv = self.__class__.__javaclass__.newInstance(*args)
jpype._jclass.IllegalArgumentException: At least one base package must be specified
```

Reproduced by me and @biczysko. 

`Jpype==0.6.3` is confirmed working and can be installed like this:

```
phenix.python -m pip uninstall JPype1 
phenix.python -m pip install JPype1==0.6.3
```

**Comment by mpwaller** [comment]
Mac OS X 10.15 fails to install JPype1==0.6.3

`In file included from native/python/include/jpype_python.h:24:
    native/common/include/jpype.h:107:10: fatal error: 'map' file not found
    #include <map>
             ^~~~~
    2 warnings and 1 error generated.
    error: command 'gcc' failed with exit status 1
    ----------------------------------------
`
Solution was to update variable:
`export MACOSX_DEPLOYMENT_TARGET=10.15`
Then re-run 
`phenix.python -m pip install JPype1==0.6.3`

**Comment by hokru** [comment]
Since yoink has effectively been dropped, jpype is no longer requirred.
