### ISSUE TITLE
Convergence criteria

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#6]
We have perturbed structures, and we are trying to get back to the original minima during the refinement or the optimisation procedure. However, the size of the perturbation is different, therefore a global number of macro cycles is not the best choice. Either too few for large perturbations, or too many for small ones. 

A "smart" convergence criteria is needed.

**Comment by biczysko** [comment]
Maybe we can add some criterium on r_factor? 
In my case it was:
  macro_cycle   0 (sites) r_factor: 0.0937
  macro_cycle   1 (sites) r_factor: 0.0780
  macro_cycle   2 (sites) r_factor: 0.0718
  macro_cycle   3 (sites) r_factor: 0.0718
  macro_cycle   4 (sites) r_factor: 0.0718
So probably converged at step 3
