### ISSUE TITLE
mmtbx problems for python3

### ISSUE THREAD

**Issue by hokru** [qrefine/qrefine#60]
Below issues are blocking the qr.charges and clustering code execution. I guess they are mmtbx and not qrefine issues, not 100% sure.
Also, the 'patches' described are just to get it to run, not to actually fix things. They may or may not introduce errors further down the line.

1.  Following error occurs e.g. from calling the `geometry_restraints_manager`: `TypeError: '<' not supported between instances of 'str' and 'empty'` in [linking_utils.py](https://github.com/cctbx/cctbx_project/blob/master/mmtbx/monomer_library/linking_utils.py#L345) and [linking_mixing.py](https://github.com/cctbx/cctbx_project/blob/master/mmtbx/monomer_library/linking_mixins.py#L643). This is because the `class1/class2` variables are not always strings.
printing [this variable](https://github.com/cctbx/cctbx_project/blob/master/mmtbx/monomer_library/linking_utils.py#L344) shows one can back a dictionary(?) and I assume python3 is more picky.
```
['other', 'common_amino_acid']
['other', 'common_amino_acid']
['other', 'common_amino_acid']
['other', 'common_amino_acid']
[  common_saccharide : False
  common_water : False
  common_element : False
  common_small_molecule : False
  common_amino_acid : False
  common_rna_dna : False
  ccp4_mon_lib_rna_dna : False
  other : False
  uncommon_amino_acid : False
  unknown : False
, 'common_amino_acid']
```
->  quick patch: enforce strings, e.g. `str(class1)`

2. This [line (in mcl.py)](https://github.com/cctbx/cctbx_project/blob/master/mmtbx/conformation_dependent_library/mcl.py#L88) tries to sort a list of iotbx atom objects, which also seems to no longer work in python3.
`TypeError: '<' not supported between instances of 'atom' and 'atom'`
-> quick patch: change sort to a loop, e.g. `for aa in aas:` (or figure out `key=operator.???`)

generously tagging everyone :)  @nwmoriarty @bkpoon @pafonine

**Comment by hokru** [comment]
3. pickle problem in iotbx's `easy_pickle` related to bytes/str issues and qrefine's `fast_interaction=True`
-> quick patch: change https://github.com/cctbx/cctbx_project/blob/master/libtbx/easy_pickle.py#L81-L83 to just `return pickle.load(_open(file_name, "rb"),encoding='bytes')`

**Comment by bkpoon** [comment]
I added the change in https://github.com/cctbx/cctbx_project/commit/30bc64fb4d503b9e695d02bf80335aa0b06d2545. Does it fix your problem? Thanks!

**Comment by hokru** [comment]
Seems resolved. Thanks!
