### ISSUE TITLE
tst_38 needs mopac

### ISSUE THREAD

**Issue by mpwaller** [qrefine/qrefine#63]
**Describe the bug**
If Mopac is not installed, then the error message is related to no being able to read a pickle file

**To Reproduce**
1. qr.test --only 38
2. look at the output
`tst_38 FAILED Cannot open pickle file "cluster_false.pkl" (Cannot open file for reading: "cluster_false.pkl"
  [Errno 2] No such file or directory: 'cluster_false.pkl')
       Total time:  33.62 (s)
`

**Expected behavior**
If mopac is not installed, a message stating that mopac should be installed. 

**Desktop (please complete the following information):**
 - OS: [e.g. Mac OS X 10.14.2]
 - Phenix Version [e.g. phenix-dev-3902]
 - qrefine Version [e.g.v1.0-176-gc3c7dd-dirty]

.

**Comment by hokru** [comment]
mopac is now build-in through cctbx
